POST  http://127.0.0.1:3000/api/auth/login
content-type: application/json

{ "userName": "ccr-cr", "password": "Claro+2023" }

################################################################

GET http://127.0.0.1:3000/api/incomes
content-type: application/json

