import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import IncomeList from '@/pages/income/IncomeList'
import { Pagination } from '@/generalComponents/Pagination'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>CCR</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        {/* <main> */}
        <IncomeList />
      </main>
      <footer>
        <Pagination />
      </footer>
    </>
  )
}
